Alvar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('AppAlvar/', include('AppAlvar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AppAlvar/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', home, name="home"),
    #Usuario
    path("login/", iniciar_sesion, name="iniciar_sesion"),
    path("logout/", cerrar_sesion, name="cerrar_sesion"),
    path("registro/", registro, name="registro"),
    path("edit/", editar_usuario, name="editar_usuario"),
    path("contra/", CambiarContra.as_view(), name="cambiar_contraseña"),
    #imagenes
    path("avatar/", agregar_avatar, name="add_avatar"),

    #clientes
    path('cliente/', ver_clientes, name="cliente"),
    path('agregar_cliente/', agregar_cliente, name="agregar_cliente"),
    path('editar_cliente/<id>', editar_cliente, name="editar_cliente"),
    path('eliminar_cliente/<int:id>/', eliminar_cliente, name='eliminar_cliente'),


    #consultas
    path('ver_consulta/', ver_consultas, name="ver_consulta"),
    path('consulta/', crear_consulta, name="crear_consulta"),
    path('editar_consulta/<id>', editar_consulta, name="editar_consulta"),
    path('eliminar_consulta/<int:id>', eliminar_consulta, name="eliminar_consulta"),

    #proyectos
    path('proyectos/', proyectos, name="proyectos"),
    path('agregar_proyecto/', agregar_proyecto, name="agregar_proyecto"),
    path('editar_proyecto/<id>/', editar_proyecto, name="editar_proyecto"),
    path('eliminar_proyecto/<int:id>/', eliminar_proyecto, name="eliminar_proyecto"),
]

AppAlvar/models.py
from django.db import models
from django.contrib.auth.models import User

class Cliente(models.Model):
    nombre = models.CharField(max_length=60)
    apellido = models.CharField(max_length=60)
    email = models.EmailField()
    edad = models.IntegerField()

    def __str__(self):
        return f"Nombre: {self.apellido} {self.nombre} -- Edad: {self.edad}"

class Proyecto(models.Model):
    nombre = models.CharField(max_length=60)
    tipo = models.CharField(max_length=60)
    comercial = models.BooleanField(null=True, blank=True)
    imagen = models.ImageField(upload_to="proyectos", null=True, blank=True)
    descripcion = models.TextField()

    def __str__(self):
        return f"Nombre: {self.nombre}"

class ProyectoFotos(models.Model):
    imagen = models.ImageField(upload_to="fotos")
    proyecto = models.ForeignKey(Proyecto, on_delete=models.CASCADE, related_name="fotos")

opciones_consulta = [
    [0, 'Consulta'],
    [1, 'Cita'],
    [2, 'Presupuesto'],
    [3, 'Otro tipo']
]
class Consulta(models.Model):
    nombre = models.CharField(max_length=60)
    email = models.EmailField()
    tipo_consulta = models.IntegerField(choices=opciones_consulta)
    mensaje = models.TextField()

    def __str__(self):
        return f"Nombre:{self.nombre} -- {self.email}"


class Avatar(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to="avatares",null=True,blank=True)

    def __str__(self):
        return f"Avatar de {self.usuario}"

AppAlvar/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,UserChangeForm

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = '__all__'

class ConsultaForm(forms.ModelForm):
    class Meta:
        model = Consulta
        fields = '__all__'

class ProyectoForm(forms.ModelForm):
    class Meta:
        model = Proyecto
        fields = '__all__'

class ProyectoFotosForm(forms.ModelForm):
    class Meta:
        model = ProyectoFotos
        fields = ['imagen']

class RegistroUsuario(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','first_name','last_name','password1','password2']

class EditarUsuario(UserChangeForm):
    password = None
    class Meta:
        model = User
        fields = ["email","first_name","last_name"]
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Correo electrónico'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Apellido'}),
        }

class AvatarForm(forms.Form):
    imagen = forms.ImageField()

AppAlvar/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from .forms import *
from django.contrib import messages
from django.core.paginator import Paginator
from django.http import Http404
#contrib.auth
from django.contrib.auth.forms import AuthenticationForm,UserCreationForm
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.views import PasswordChangeView
#LoginRequired
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

#-------------------USUARIOS---------------------#
#INICIAR SESION
def iniciar_sesion(request):
    if request.method == "POST":
        formulario = AuthenticationForm(request, data=request.POST)
        if formulario.is_valid():
            info_dict = formulario.cleaned_data
            usuario = authenticate(username=info_dict["username"],password=info_dict["password"])
            if usuario:
                login(request,usuario)
                messages.success(request, "Sesion Iniciada")
                return redirect(to="home")
        else:
            return render(request, "AppAlvar/home.html")
    
    else:
        formulario = AuthenticationForm()
    
    return render(request, "AppAlvar/registro/inicio_sesion.html", {'form':formulario})

#CERRAR SESION
@login_required
def cerrar_sesion(request):
    logout(request)
    messages.success(request, "Sesion Finalizada")
    return redirect(to="home")

#REGISTRARSE
def registro(request):
    data = {
        'form': RegistroUsuario()
    }

    if request.method == "POST":
        formulario = RegistroUsuario(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            user = authenticate(username=formulario.cleaned_data["username"],
                                password=formulario.cleaned_data["password1"])
            login(request, user)
            messages.success(request, "Te has registrado correctamente")
            return redirect(to='home')
        else:
            data['form'] = formulario
    
    return render(request, "AppAlvar/registro/registro.html", data)

#UPDATE
@login_required
def editar_usuario(request):
    usuario = request.user
    if request.method == "POST":
        formulario = EditarUsuario(request.POST)
        if formulario.is_valid():
            info = formulario.cleaned_data
            usuario.email = info["email"]
            usuario.first_name = info["first_name"]
            usuario.last_name = info["last_name"]
            usuario.save()
            messages.success(request, "Cambios Guardados")
            return redirect(to="home")
    else:
        formulario = EditarUsuario()
    return render(request, "AppAlvar/registro/editar_usuario.html", {"form":formulario})

#CAMBIAR CONTRASEÑA
class CambiarContra(LoginRequiredMixin, PasswordChangeView):
    template_name = "AppAlvar/registro/cambiar_contra.html"
    success_url = "/AppAlvar/"

#AVATAR
@login_required
def agregar_avatar(request):
    if request.method == "POST":
        formulario = AvatarForm(request.POST, request.FILES)
        if formulario.is_valid():
            info = formulario.cleaned_data
            usuario_actual = User.objects.get(username=request.user)
            nuevo_avatar = Avatar(usuario=usuario_actual,imagen=info["imagen"])
            nuevo_avatar.save()
            messages.success(request, "Avatar Cambiado")
            return redirect(to="home")
    else:
        formulario = AvatarForm()
    
    return render(request, "AppAlvar/registro/nuevo_avatar.html", {"form":formulario})

#--------------------INICIO----------------------------
def home(request):
    return render(request, "AppAlvar/home.html")



#-----------------------CLIENTES-------------------------
#CREATE
@login_required
def agregar_cliente(request):
    data = {
        'form':ClienteForm()
    }

    if request.method == "POST":
        formulario =ClienteForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Cliente creado")
            return redirect(to="cliente")
        else:
            data['form'] = formulario
            
    return render(request, 'AppAlvar/cliente/agregar.html', data)


#READ
@login_required
def ver_clientes(request):
    cliente = Cliente.objects.all()
    page = request.GET.get('page', 1)

    try:
        paginator = Paginator(cliente, 8)
        cliente = paginator.page(page)
    except:
        raise Http404

    data = {
        'entity':cliente,
        'paginator': paginator
    }

    return render(request, 'AppAlvar/cliente/ver.html', data)


#UPDATE
@login_required
def editar_cliente(request,id):
    cliente = get_object_or_404(Cliente, id=id)
    data = {
        'form':ClienteForm(instance=cliente)
    }

    if request.method == "POST":
        formulario = ClienteForm(data=request.POST, instance=cliente)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Modificado correctamente")
            return redirect(to="cliente")
        else:
            data['form'] = formulario

    return render(request, "AppAlvar/cliente/modificar.html", data)


#DELETE
@login_required
def eliminar_cliente(request, id):
    cliente = get_object_or_404(Cliente, id=id)
    cliente.delete()
    messages.success(request, "Cliente eliminado correctamente")
    return redirect("cliente")


#-----------------------CONSULTAS---------------------------
#CREATE
def crear_consulta(request):
    data = {
        'form': ConsultaForm()
    }

    if request.method == "POST":
        formulario = ConsultaForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Consulta creada")
            return redirect(to="crear_consulta")
        else:
            data['form'] = formulario
            
    return render(request, 'AppAlvar/consulta.html', data)


#READ
@login_required
def ver_consultas(request):
    consulta = Consulta.objects.all()
    page = request.GET.get('page', 1)

    try:
        paginator = Paginator(consulta, 8)
        consulta = paginator.page(page)
    except:
        raise Http404

    data = {
        'entity': consulta,
        'paginator': paginator
    }

    return render(request, 'AppAlvar/consulta/ver.html', data)


#UPDATE
@login_required
def editar_consulta(request,id):
    consulta = get_object_or_404(Consulta, id=id)
    data = {
        'form': ConsultaForm(instance=consulta)
    }

    if request.method == "POST":
        formulario = ConsultaForm(data=request.POST, instance=consulta)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Modificado correctamente")
            return redirect(to="ver_consulta")
        else:
            data['form'] = formulario

    return render(request, "AppAlvar/consulta/modificar.html", data)


#DELETE
@login_required
def eliminar_consulta(request,id):
    constulta = get_object_or_404(Consulta, id=id)
    constulta.delete()
    messages.success(request, "Eliminado correctamente")
    return redirect(to="ver_consulta")


#-----------------------PROYECTOS---------------------------
#CREATE
@login_required
def agregar_proyecto(request):
    data = {
        'form': ProyectoForm()
    }

    if request.method == "POST":
        formulario = ProyectoForm(data=request.POST, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Proyecto Creado")
            return redirect(to="proyectos")
        else:
            data['form'] = formulario

    return render(request, "AppAlvar/proyecto/agregar.html", data)


#READ
def proyectos(request):
    proyectos = Proyecto.objects.all()
    page = request.GET.get('page', 1)

    try:
        paginator = Paginator(proyectos, 8)
        proyectos = paginator.page(page)
    except:
        raise Http404

    data = {
        'entity': proyectos,
        'paginator': paginator
    }

    return render(request, 'AppAlvar/proyectos.html', data)


#UPDATE
@login_required
def editar_proyecto(request,id):
    proyecto = get_object_or_404(Proyecto, id=id)
    data = {
        'form': ProyectoForm(instance=proyecto)
    }

    if request.method == "POST":
        formulario = ProyectoForm(data=request.POST, instance=proyecto, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Modificado correctamente")
            return redirect(to="proyectos")
        else:
            data['form'] = formulario

    return render(request, "AppAlvar/proyecto/modificar.html", data)


#DELETE
@login_required
def eliminar_proyecto(request,id):
    proyecto = get_object_or_404(Proyecto, id=id)
    proyecto.delete()
    messages.success(request, "Eliminado correctamente")
    return redirect(to="proyectos")

AppAlvar/templates/AppAlvar/consulta.html
<!DOCTYPE html>
{% extends 'AppAlvar/padre.html' %}
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Registro de usuario</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    </head>
{% load static %}

{% block js %}
<script>
    function eliminarCliente(id) {
        Swal.fire({
            title: "¿Estás seguro?",
            text: "Esta acción no se puede deshacer",
            icon: "question",
            showCancelButton: true,
            cancelButtonText: "No, Cancelar",
            confirmButtonText: "Si, Eliminar",
            reverseButtons: true,
            confirmButtonColor: "#dc3545",
        }).then(function(result) {
            if (result.isConfirmed) {
                // Redireccionar a la URL de eliminación del cliente
                window.location.href = "../eliminar_cliente/" + id + "/";
            }
        });
    }
</script>
{% endblock %}
{% block css %} {% endblock %}
{% block contenido %}
{% load crispy_forms_tags %}
<body>
    <br>
<div class="d-flex justify-content-end">
    {% if user.is_staff or user.is_superuser %}
    <a href="{% url 'ver_consulta' %}" id="guardar" class=" btn btn-primary">Ver Consulta</a>
    {% endif %}
</div>
<div class="container">
            <br>
        <div class="row">
            <div class="col-12 col-md-6 offset-md-3">
            <div class="card">
            <div class="card-body">
                <h2> Consultas</h2>
                <hr>
                <form action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <hr>
                    <div class="d-flex justify-content-end">
                        <button type="reset" class="btn btn-secondary">Limpiar</button>
                        &nbsp;
                        <button type="submit" id="guardar" class=" btn btn-primary">Guardar</button>
                    </div>
                </form>
        </div>
        </div>
        </div>
        </div>
        {{ mensaje }}
        </div>
        {% endblock %}
        <script src="" async defer></script>
    </body>
</html>

AppAlvar/templates/AppAlvar/home.html
{% extends 'AppAlvar/padre.html' %}

{% load static %}

{% block js %} {% endblock %}
{% block css %} {% endblock %}

{% block contenido %}
{% load crispy_forms_tags %}
<div>
    {{ mensaje }}
</div>




{% endblock %}

AppAlvar/templates/AppAlvar/padre.html
<!doctype html>
<html lang="es">
<head>
    {% load static%}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>ALVAR Arquitectura</title>
    {% block css %}
    {% endblock %}
    <link rel="stylesheet" href="{% static 'AppAlvar/css/estilos.css' %}">
</head>
<body >
<header id="header">
    <img src="{% static 'AppAlvar/img/menuiconwhite.png' %}" alt="menu" class="menu" id="menu">
    <div class="contenedor_logo">
        <img src="{% static 'AppAlvar/img/logo2.png' %}" alt="logo" class="logo">
        <a href="{% url 'home' %}"><button style="background-color: transparent; border: 2px solid white; color: white; transition: background-color 0.3s;"
            onmouseover="this.style.backgroundColor='#FFFFFF10'" onmouseout="this.style.backgroundColor='transparent'" class="btn btn-primary">Inicio</button></a>
    </div>
    <div>
        <nav id="nav">
            <ul>
                <li>
                    
                </li>
                <li>
                    <a href="{% url 'crear_consulta' %}"><button style="background-color: transparent; border: 2px solid white; color: white; transition: background-color 0.3s;"
                        onmouseover="this.style.backgroundColor='#FFFFFF10'" onmouseout="this.style.backgroundColor='transparent'" class="btn btn-primary">Consulta</button></a>
                </li>
                <li>
                    <a href="{% url 'proyectos' %}"><button style="background-color: transparent; border: 2px solid white; color: white; transition: background-color 0.3s;"
                        onmouseover="this.style.backgroundColor='#FFFFFF10'" onmouseout="this.style.backgroundColor='transparent'" class="btn btn-primary">Proyectos</button></a>
                </li>
                {% if user.is_staff or user.is_superuser %}
                <li>
                    <a href="{% url 'cliente' %}"><button style="background-color: transparent; border: 2px solid white; color: white; transition: background-color 0.3s;"
                        onmouseover="this.style.backgroundColor='#FFFFFF10'" onmouseout="this.style.backgroundColor='transparent'" class="btn btn-primary">Clientes</button></a>
                </li>
                {% endif %}
                {% if user.is_authenticated %}
                <li>
                    <a href="{% url 'editar_usuario' %}">{{user.username}}</a>
                </li>
                <a href="{% url 'add_avatar' %}"><img src="{{user.avatar_set.last.imagen.url}}" alt="Avatar" width="50" height="50"></a>
                <li>
                    <a href="{% url 'cambiar_contraseña' %}">Cambiar contraseña</a>
                </li>
                <li>
                    <a href="{% url 'cerrar_sesion' %}"><button style="background-color: transparent; border: 2px solid white; color: white; transition: background-color 0.3s;"
                        onmouseover="this.style.backgroundColor='#FFFFFF10'" onmouseout="this.style.backgroundColor='transparent'" class="btn btn-primary">Cerrar Sesion</button></a>
                </li>
                {% else %}
                <li>
                    <a href="{% url 'iniciar_sesion' %}"><button style="background-color: transparent; border: 2px solid white; color: white; transition: background-color 0.3s;"
                        onmouseover="this.style.backgroundColor='#FFFFFF10'" onmouseout="this.style.backgroundColor='transparent'" class="btn btn-primary">Iniciar Sesion</button></a> |
                    <a href="{% url 'registro' %}"><button style="background-color: transparent; border: 2px solid white; color: white; transition: background-color 0.3s;"
                        onmouseover="this.style.backgroundColor='#FFFFFF10'" onmouseout="this.style.backgroundColor='transparent'" class="btn btn-primary">Registrarse</button></a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</header>
<div id="contenido">
    {% block contenido%}

    {% endblock%}
</div>
<footer>
    <footer>
        <div class="logo_footer">
            <img src="{% static 'AppAlvar/img/logo1.png' %}" width="500px" alt="logo">
        </div>
    </footer>
</footer>
<script src="{% static 'AppAlvar/js/menu.js' %}"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

{% if messages %}
    {% for m in messages %}
        <script>
            Swal.fire({
                "title": "Felicitaciones",
                "text": "{{m}}",
                "icon": "success",
            })
        </script>
    {% endfor %}
{% endif %}

{% block js %}

{% endblock %}


</body>
</html>

AppAlvar/templates/AppAlvar/paginator.html
{% if paginator.num_pages > 1%}
<div class="d-flex justify-content-center">
    <ul class="pagination">
        {% if entity.has_previous %}
            <li class="page-item d-none d-sm-block"><a class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></li>
        {% endif %}
        {% for page in paginator.page_range %}
            {% if forloop.last and page != entity.number and paginator.num_pages > 7 %} 
                {% if entity.next_page_number != paginator.num_pages%}
                <li class="page-item">
                    <a class="page-link" href="?page={{ entity.number | add:1}}#pagtable">...</a>
                </li>
                {% endif %}
            <li class="page-item">
                    <a class="page-link" href="?page={{paginator.num_pages}}#pagtable">{{paginator.num_pages}}</a>
            </li>
            {% endif %}
            {% if page == entity.number and page > 7 %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page | add:-1 }}#pagtable">...</a>
            </li>    
            {% endif %}
            {% if page < 7 or page == entity.number %}
            <li class="page-item {% if page == entity.number %}active{% endif %}">
                <a class="page-link" href="?page={{ page }}#pagtable">{{ page }}</a>
            </li>
            {% endif %}
        {% endfor %}
        {% if entity.has_next %}
            <li class="page-item d-none d-sm-block">
                <a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a>
            </li>
        {% endif %}
    </ul>
</div>
<div class="d-flex justify-content-center d-sm-none">            
    {% if entity.has_previous %}
        <span class="page-item"><a  class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></span>
    {% endif %}
    {% if entity.has_next %}
        <span class="page-item"><a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a></span>
    {% endif %}
    <br>
    <br>
</div>
{% endif %}

AppAlvar/templates/AppAlvar/proyectos.html
{% extends 'AppAlvar/padre.html' %}

{% block js %}
<script>
    function eliminarProyecto(id) {
        Swal.fire({
            title: "¿Estás seguro?",
            text: "Esta acción no se puede deshacer",
            icon: "question",
            showCancelButton: true,
            cancelButtonText: "No, Cancelar",
            confirmButtonText: "Si, Eliminar",
            reverseButtons: true,
            confirmButtonColor: "#dc3545",
        }).then(function(result) {
            if (result.isConfirmed) {
                // Redireccionar a la URL de eliminación del cliente
                window.location.href = "../eliminar_proyecto/" + id +"/";
            }
        });
    }
</script>
{% endblock %}
{% block css %}
{% endblock %}

{% block contenido %}
<br>
<div class="d-flex justify-content-end">
    {% if user.is_staff or user.is_superuser %}
    <a href="{% url 'agregar_proyecto' %}" id="guardar" class=" btn btn-primary">Crear Proyecto</a>
    {% endif %}
</div>
<br>
<div class="galeria">

{% for p in entity %}
<div class="producto">
    <div class="contenedor">
        {% if p.imagen %}
        <img src="{{ p.imagen.url }}" alt="yoga">
        {% endif %}
    </div>

    <div class="detalles">
        <h5>{{p.nombre | capfirst}}</h5>
        <h2>{{p.tipo | title}}</h2>
        {% if p.comercial %}
        <h3>Comercial</h3>
        {% else %}
        <h3>Residencial</h3>
        {% endif %}
        <h6>{{ p.descripcion | capfirst }}</h6>
    </div>
    <div class="d-flex justify-content-end">
    {% if user.is_superuser %}
    <a href="#" onclick="eliminarProyecto('{{ p.id }}')"class="btn btn-danger btn-sm">Borrar</a>
    {% endif %}
    &nbsp;
    {% if user.is_superuser or user.is_staff %}
    <a href="{% url 'editar_proyecto' p.id %}" id="guardar" class=" btn btn-primary btn-sm">Editar</a>
    {% endif %}
    </div>
    
</div>
{% endfor %}
</div>
<hr>
<div>
    {% include 'AppAlvar/paginator.html' %}
</div>
{{ mensaje }}


{% endblock %}